# Generated by Django 5.1.4 on 2025-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('is_working', models.BooleanField(default=False, verbose_name='Рабочий')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверен')),
                ('file', models.FileField(blank=True, null=True, upload_to='vpn/', verbose_name='Файл')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата скачивания')),
            ],
            options={
                'verbose_name': 'VPN-конфиг',
                'verbose_name_plural': 'VPN-конфиги',
            },
        ),
    ]
