# Generated by Django 5.1.4 on 2025-11-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnconfig',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
